version: "3.9"
services:
  #frontend
  frontend:
    container_name: cnsp-frontend
    image: cnsp-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  # backend
  backend:
    container_name: cnsp-backend
    image: cnsp-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./backend/.env
