name: "Deploy to Google Cloud Run"
"on":
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/cnsp-backend:latest
          build-args: |
            HTTP_PORT=8080

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/cnsp-backend:latest
          service: cnsp-backend-service
          region: us-central1
          platform: managed
          allow-unauthenticated: true
          env_vars: |
            FIREBASE_PROJECTID=${{ secrets.FIREBASE_PROJECTID }}
            FIREBASE_PRIVATEKEYID=${{ secrets.FIREBASE_PRIVATEKEYID }}
            FIREBASE_PRIVATEKEY=${{ secrets.FIREBASE_PRIVATEKEY }}
            FIREBASE_CLIENTEMAIL=${{ secrets.FIREBASE_CLIENTEMAIL }}
            FIREBASE_CLIENTID=${{ secrets.FIREBASE_CLIENTID }}
            FIREBASE_CLIENTx509CERTURL=${{ secrets.FIREBASE_CLIENTx509CERTURL }}
