name: Build and Deploy Backend Image to Google Cloud Run
"on":
  push:
    branches:
      - main
jobs:
  setup_build_deploy_backend_gcr:
    name: Build and Deploy Backend Image to Google Cloud Run
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: cnsp-backend
      PROJECT_ID: cnsp-backend-418915
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_IDD }}

      - name: Build Docker image
        run: cd ./backend && docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker gcr.io --quiet

      - name: Push Docker Image to Container Registry (GCR)
        run: |-
          gcloud auth print-access-token 
          docker login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
