name: Build and Deploy Backend Image to Google Cloud Run
"on":
  push:
    branches:
      - main
jobs:
  setup_build_deploy_backend_gcr:
    name: Build and Deploy Backend Image to Google Cloud Run
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: cnsp-backend
      PROJECT_ID: cnsp-backend-418915
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_IDD }}
          export_default_credentials: true

      - name: Build Docker image
        run: cd ./backend && docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet

      - name: Push Docker Image to COntainer Registry (GCR)
        run: |-
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
