name: "Deploy to Google Cloud Run"
"on":
  push:
    branches:
      - main
jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: "app"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          export_default_credentials: true

      - name: Build and Push Docker image
        run: |
          gcloud auth configure-docker
          docker build -t gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/cnsp-backend:latest ./app/backend/
          docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/cnsp-backend:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cnsp-backend-service --image gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/cnsp-backend:latest --platform managed --region us-central1 --allow-unauthenticated --update-env-vars FIREBASE_PROJECTID=${{ secrets.FIREBASE_PROJECTID }},FIREBASE_PRIVATEKEYID=${{ secrets.FIREBASE_PRIVATEKEYID }},FIREBASE_PRIVATEKEY=${{ secrets.FIREBASE_PRIVATEKEY }},FIREBASE_CLIENTEMAIL=${{ secrets.FIREBASE_CLIENTEMAIL }},FIREBASE_CLIENTID=${{ secrets.FIREBASE_CLIENTID }},FIREBASE_CLIENTx509CERTURL=${{ secrets.FIREBASE_CLIENTx509CERTURL }}
